# Allow ICMP
netsh advfirewall firewall add rule name="Allow ICMPv4" protocol=icmpv4:8,any dir=in action=allow
netsh advfirewall firewall add rule name="Allow ICMPv6" protocol=icmpv6:8,any dir=in action=allow

# Install IIS with ASP.Net support
Install-WindowsFeature -name Web-Server, Web-Asp-Net45 -IncludeManagementTools

# Create a default file containing WAN IP, ipconfig output, and a dump of request headers
$HTML = "<pre>" + $ENV:COMPUTERNAME + "<br/>"
$HTML += "WAN IP: $(irm ifconfig.me) <br/><hr/>"
$HTML += "Request headers: <br/>"
$HTML += '<%= Request.Headers.ToString().Replace("&","<br/>") %></pre>'
$HTML > C:\inetpub\wwwroot\default.aspx

# Install Certificate - leebug.biz
mkdir c:\Temp1
Add-Content -Value "MIIKLgYJKoZIhvcNAQcCoIIKHzCCChsCAQExADALBgkqhkiG9w0BBwGgggoDMIIE5TCCA82gAwIBAgISBJzXfdaOHUmy0N2hv1JkV4yaMA0GCSqGSIb3DQEBCwUAMDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJSMzAeFw0yNDA0MTUwMzQ4NThaFw0yNDA3MTQwMzQ4NTdaMBcxFTATBgNVBAMMDCoubGVlYnVnLmJpejCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMiN6O9RIWtGyq2vkyW/BIkx9Dp+wQljr3ldzhOz1yHAC14scJNJCRkIqgr+xuOl4iRBzU9WrlX1a/Xx80RWqln4llOH5mp4JLlYbrYI6hyldKIx1h4hME1Qr+3fwPhW4tbSKzgP7wvbKwKS2uiCnEgSu9qfEiaEGr1856OcfJPuOi2IHSinXYvFjyR/r3okXbXjXOOhnMuxa38z7XoxGyo+wSXxyFYXLFwAF6BpXcBB9Mv56JqSBXgk4XV+X8lG70KUGnshRioOW3/KYf03onHqX3BU3AIy4C1JBTlAY9Ut/lhqRL+gfRqpJXJ3QhVdcwQjKVY50LB+pwlOPUhgqqsCAwEAAaOCAg4wggIKMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU4Ol+2eHZTgQn9ya1gRysIJvkPNwwHwYDVR0jBBgwFoAUFC6zF7dYVsuuUAlA5h+vnYsUwsYwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUFBzABhhVodHRwOi8vcjMuby5sZW5jci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9yMy5pLmxlbmNyLm9yZy8wFwYDVR0RBBAwDoIMKi5sZWVidWcuYml6MBMGA1UdIAQMMAowCAYGZ4EMAQIBMIIBBAYKKwYBBAHWeQIEAgSB9QSB8gDwAHYAPxdLT9ciR1iUHWUchL4NEu2QN38fhWrrwb8ohez4ZG4AAAGO4BZBZwAABAMARzBFAiEA7nMl220jeWKuAx5jGseUBBatk7R4+0Z/BVxSbWawK8wCIBd61CyFC5X/uz2VJsXeJ7GD9AXq7qvLZ42Aw5EsbWglAHYA7s3QZNXbGs7FXLedtM0TojKHRny87N7DUUhZRnEftZsAAAGO4BZBZAAABAMARzBFAiEAmw3O/zjcJz3LKvHinUjgdN4Ryc5Q7nPvFeC8oDmGmF8CICY5CeQqS2UQVsmcOf9Rm/M8JFAWwSYtdqgipg12QusfMA0GCSqGSIb3DQEBCwUAA4IBAQBOrnX8AOL4KY9vXswpTrXg44NBP88CwZiyiQvuBVLVTC1e+L2JSM8/hMi4lf+o31I5ecGa4jG92bQ7hmXbxCcB6qyHfITgMMXfPLMCg8GRNJ+FtNX92OMyd5ARpghSXPSh4Jl/V71FsmTz7B5Vpw9T+wkekXRqIpIR+kJLvKaaqVgydGY3hzrFeWwCqzj/czSE5oLpNuL0RmA+oa0AUdxx2FufMrAmnwBqrW2sfuFGnC28RGFMuMOr/bqABSYyPTfe9i1eHNF7uSDM/wy4vUPebiI9CW8Y+3ZwtlJkUASj6Rdywv7ZPxsryBW8ECOocWpqLVfsfn1bZpufFge4OwagMIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAwTzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2VhcmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAwWhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3MgRW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cPR5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdxsxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8ZutmNHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxgZ3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG/kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMCAYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaAFHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcwAoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRwOi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQBgt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6WPTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wlikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQzCkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BImlJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1OyK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90IdshCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6ZvMldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqXnLRbwHOoq7hHwjEA"
certutil -decode c:\temp1\pfx-encoded-bytes.txt c:\temp1\backend.pfx
certutil -f -p poshacme -importpfx c:\temp1\backend.pfx

# Remove default iisstart.htm file
Remove-Item "C:\inetpub\wwwroot\iisstart.htm"

# Configure IIS HTTPS binding using previously imported self signed certificate
$Cert = Get-ChildItem Cert:\LocalMachine\My\ | ? Subject -eq "CN=backend.fabrikam.com"
New-WebBinding -Name "Default Web Site" -Protocol https -Port 443
(Get-WebBinding -Name "Default Web Site" -Protocol https -Port 443).AddSslCertificate($Cert.Thumbprint, "my")

# Remove http binding
Remove-WebBinding -Protocol http -Port 80
